server:
  port: 8901

spring:
  application:
    name: admin-service
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/ttotw?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 9269
    hikari:
      minimumIdle: 5
      maximumPollSize: 20
      idleTimeout: 30000
      pollName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true